version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: main
  assignees:
  - textbook
  labels:
  - dependencies
  versioning-strategy: increase
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 15.0.0
  - dependency-name: ts-loader
    versions:
    - 9.0.0
  - dependency-name: webdriverio
    versions:
    - 7.0.1
    - 7.0.2
    - 7.4.2
  - dependency-name: "@types/webpack"
    versions:
    - 5.0.0
