version: 2
jobs:
  build:
    docker:
      - image: circleci/node:erbium-browsers
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
            - node-deps-
      - run:
          name: Install
          command: npm ci
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - "~/.npm"
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Test
          command: npm test
      - run:
          name: Build
          command: npm run build
      - run:
          name: End-to-End
          command: npm run e2e
      - run:
          name: Docker Build
          command: docker build .
      - store_test_results:
          path: reports
workflows:
  version: 2
  build:
    jobs:
      - build
